## 需要安装REST Client插件
@baseUrl = http://localhost:3000/api

# # @name 测试用例
# GET  {{baseUrl}}/car HTTP/1.1
# Content-Type: application/json

# # @name 测试用例2 
# GET  {{baseUrl}}/car/nest?test=1&bundle_id=demo&msg=123123 HTTP/1.1

# # @name 测试用例3通配符
# GET  {{baseUrl}}/car/12/test HTTP/1.1
# Content-Type: application/json

# # @name 获取状态码
# GET {{baseUrl}}/car/code HTTP/1.1

# # @name 同步请求
# GET {{baseUrl}}/car/promise/3 HTTP/1.1


# # @name 同步请求
# POST  {{baseUrl}}/car HTTP/1.1
# Content-Type: application/json

# {
#     "name":"张三",
#     "age":1,
#     "breed":"中国"
# }

# # @name 创建数据集合
# POST  {{baseUrl}}/car/createCat HTTP/1.1
# Content-Type: application/json

# {
#     "name":"张三",
#     "age":20,
#     "breed":"中国"
# }


# # @name 获取数据集合
# GET   {{baseUrl}}/car/findCar?id=3 HTTP/1.1
# Content-Type: application/json


# # @name 创建数据集合
# GET   {{baseUrl}}/bus/asyncCarService HTTP/1.1
# Content-Type: application/json



# # @name 测试为什么要使用全局变量
# GET   {{baseUrl}}/car/busSay HTTP/1.1
# Content-Type: application/json


# # @name 获取token
# GET   {{baseUrl}}/auth HTTP/1.1
# Content-Type: application/json

# # @name 解析token
# GET   {{baseUrl}}/auth/tokenStr HTTP/1.1
# Content-Type: application/json
# token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1aWQiOjEsInJpZCI6WzFdfQ.Pyy9B18YOPk_fdQQnC4gajTiZaIe8kjr6h9Rj7ox1V2cfbqZ_yX7iUqRtmSNBHUxCsbeqADlzNblI4uozRD38Q


# # @name 解析token
# GET    {{baseUrl}}/car/findCom HTTP/1.1
# Content-Type: application/json

# @name 解析token
POST   {{baseUrl}}/car/create HTTP/1.1
Content-Type: application/json

{
  "name":"1qe123123213",
  "employees":[{
    "name":"12312312",
    "age":12,
    "address":"shangs123132132da"
  }
  ]
}